//types
export enum ActionType {
  SET_CURRENT_USER = 'SET_CURRENT_USER',
  SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS',
  SIGN_IN_ERROR = 'SIGN_IN_ERROR',
  SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS',
  SIGN_UP_ERROR = 'SIGN_UP_ERROR',
  PASSWORD_RECOVERY_SUCCESS = 'PASSWORD_RECOVERY_SUCCESS',
  PASSWORD_RECOVERY_ERROR = 'PASSWORD_RECOVERY_ERROR',
}
